import { promises as fs } from "node:fs";
import path from "node:path";

export const DEFAULT_EXPLORE_AUDIT_PATH = ".ori/explore-audit.jsonl";

export type ExploreAuditNote = {
  title: string;
  score: number;
  pprScore: number;
  seedScore: number | null;
  warmthScore: number | null;
  source: string;
};

export type ExploreAuditPass = {
  query: string;
  depth: number;
  notesFound: number;
  newNotesAdded: number;
  newNotes: string[];
  elapsedMs: number;
};

export type ExploreAuditEvent = {
  timestamp: string;
  query: string;
  intent: string;
  llmProvider: string;
  llmModel: string;
  recursive: boolean;
  recursionDepth: number;
  converged: boolean;
  totalElapsedMs: number;
  /** Notes from initial flat retrieval (pass 0, no recursion) */
  flatResults: ExploreAuditNote[];
  /** Final results after recursion */
  finalResults: ExploreAuditNote[];
  /** Notes that recursion added (in final but not in flat) */
  recursionGains: ExploreAuditNote[];
  /** Notes that recursion displaced (in flat but not in final) */
  recursionLosses: ExploreAuditNote[];
  /** Sub-questions generated by LLM at each depth */
  subQueries: string[];
  /** Per-pass breakdown */
  perPassResults: ExploreAuditPass[];
  /** Graph paths discovered */
  pathCount: number;
  /** Total unique candidates scored across all passes */
  totalCandidatesScored: number;
};

export function isExploreAuditEnabled(): boolean {
  const value = process.env.ORI_EXPLORE_AUDIT;
  if (!value) return false;
  return value !== "0" && value.toLowerCase() !== "false";
}

function getExploreAuditPath(vaultRoot: string): string {
  const override = process.env.ORI_EXPLORE_AUDIT_PATH;
  return path.resolve(vaultRoot, override && override.trim() ? override : DEFAULT_EXPLORE_AUDIT_PATH);
}

export async function logExploreAudit(
  vaultRoot: string,
  event: ExploreAuditEvent,
): Promise<void> {
  const logPath = getExploreAuditPath(vaultRoot);
  await fs.mkdir(path.dirname(logPath), { recursive: true });
  await fs.appendFile(logPath, JSON.stringify(event) + "\n", "utf8");
}

export async function loadExploreAudit(
  vaultRoot: string,
): Promise<ExploreAuditEvent[]> {
  const logPath = getExploreAuditPath(vaultRoot);
  let raw: string;
  try {
    raw = await fs.readFile(logPath, "utf8");
  } catch {
    return [];
  }

  const events: ExploreAuditEvent[] = [];
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      events.push(JSON.parse(trimmed) as ExploreAuditEvent);
    } catch {
      // Ignore malformed lines
    }
  }
  return events;
}

